/*
Copyright 2026 Alexis Lowe.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package onionbalance

import (
	"fmt"
	"strings"

	"github.com/chimbosonic/tor-gateway/internal/tor"
)

// Render produces a syntactically valid onionbalance v3 config.yaml.
//
// The master argument is the front-facing .onion (derived by the operator
// from the user-supplied master ed25519 key). The backends slice may be
// empty — onionbalance starts on an empty instances list and the
// superdescriptor will simply advertise no intro points until obrefresh
// populates the pool.
//
// keyPath is the in-pod path where the master Secret is mounted; it is
// written into the services[].key field verbatim.
//
// Output is deterministic — same inputs always produce byte-identical
// YAML, so obrefresh can detect "no change" by string comparison.
func Render(master tor.OnionAddress, backends []tor.OnionAddress, keyPath string) (string, error) {
	if keyPath == "" {
		return "", fmt.Errorf("onionbalance: keyPath is required")
	}
	var b strings.Builder
	b.WriteString("# generated by tor-gateway operator — do not edit by hand\n")
	b.WriteString("services:\n")
	b.WriteString("- key: ")
	b.WriteString(keyPath)
	b.WriteString("\n")
	if len(backends) == 0 {
		b.WriteString("  instances: []\n")
		return b.String(), nil
	}
	b.WriteString("  instances:\n")
	for i, a := range backends {
		fmt.Fprintf(&b, "  - address: %s\n    name: backend-%d\n", a.String(), i)
	}
	fmt.Fprintf(&b, "# master: %s\n", master.String())
	return b.String(), nil
}
