apiVersion: policy.torgateway.io/v1alpha1
kind: TorServicePolicy
metadata:
  labels:
    app.kubernetes.io/name: tor-gateway
    app.kubernetes.io/managed-by: kustomize
  name: torservicepolicy-sample
spec:
  # TODO(user): Add fields here
