//go:build !ignore_autogenerated

/*
Copyright 2026 Alexis Lowe.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientsSecretRef) DeepCopyInto(out *ClientsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientsSecretRef.
func (in *ClientsSecretRef) DeepCopy() *ClientsSecretRef {
	if in == nil {
		return nil
	}
	out := new(ClientsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRotationSpec) DeepCopyInto(out *KeyRotationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRotationSpec.
func (in *KeyRotationSpec) DeepCopy() *KeyRotationSpec {
	if in == nil {
		return nil
	}
	out := new(KeyRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterKeySecretRef) DeepCopyInto(out *MasterKeySecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterKeySecretRef.
func (in *MasterKeySecretRef) DeepCopy() *MasterKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(MasterKeySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnionBalancePolicy) DeepCopyInto(out *OnionBalancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnionBalancePolicy.
func (in *OnionBalancePolicy) DeepCopy() *OnionBalancePolicy {
	if in == nil {
		return nil
	}
	out := new(OnionBalancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OnionBalancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnionBalancePolicyList) DeepCopyInto(out *OnionBalancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OnionBalancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnionBalancePolicyList.
func (in *OnionBalancePolicyList) DeepCopy() *OnionBalancePolicyList {
	if in == nil {
		return nil
	}
	out := new(OnionBalancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OnionBalancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnionBalancePolicySpec) DeepCopyInto(out *OnionBalancePolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	out.RefreshInterval = in.RefreshInterval
	out.MasterKeySecretRef = in.MasterKeySecretRef
	if in.BackendResources != nil {
		in, out := &in.BackendResources, &out.BackendResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.FrontendResources != nil {
		in, out := &in.FrontendResources, &out.FrontendResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnionBalancePolicySpec.
func (in *OnionBalancePolicySpec) DeepCopy() *OnionBalancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(OnionBalancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnionBalancePolicyStatus) DeepCopyInto(out *OnionBalancePolicyStatus) {
	*out = *in
	if in.Ancestors != nil {
		in, out := &in.Ancestors, &out.Ancestors
		*out = make([]v1.PolicyAncestorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnionBalancePolicyStatus.
func (in *OnionBalancePolicyStatus) DeepCopy() *OnionBalancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(OnionBalancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorClientAuthPolicy) DeepCopyInto(out *TorClientAuthPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorClientAuthPolicy.
func (in *TorClientAuthPolicy) DeepCopy() *TorClientAuthPolicy {
	if in == nil {
		return nil
	}
	out := new(TorClientAuthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorClientAuthPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorClientAuthPolicyList) DeepCopyInto(out *TorClientAuthPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TorClientAuthPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorClientAuthPolicyList.
func (in *TorClientAuthPolicyList) DeepCopy() *TorClientAuthPolicyList {
	if in == nil {
		return nil
	}
	out := new(TorClientAuthPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorClientAuthPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorClientAuthPolicySpec) DeepCopyInto(out *TorClientAuthPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	out.ClientsSecretRef = in.ClientsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorClientAuthPolicySpec.
func (in *TorClientAuthPolicySpec) DeepCopy() *TorClientAuthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TorClientAuthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorClientAuthPolicyStatus) DeepCopyInto(out *TorClientAuthPolicyStatus) {
	*out = *in
	if in.Ancestors != nil {
		in, out := &in.Ancestors, &out.Ancestors
		*out = make([]v1.PolicyAncestorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorClientAuthPolicyStatus.
func (in *TorClientAuthPolicyStatus) DeepCopy() *TorClientAuthPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TorClientAuthPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorServicePolicy) DeepCopyInto(out *TorServicePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorServicePolicy.
func (in *TorServicePolicy) DeepCopy() *TorServicePolicy {
	if in == nil {
		return nil
	}
	out := new(TorServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorServicePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorServicePolicyList) DeepCopyInto(out *TorServicePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TorServicePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorServicePolicyList.
func (in *TorServicePolicyList) DeepCopy() *TorServicePolicyList {
	if in == nil {
		return nil
	}
	out := new(TorServicePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorServicePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorServicePolicySpec) DeepCopyInto(out *TorServicePolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	if in.PoWDefensesEnabled != nil {
		in, out := &in.PoWDefensesEnabled, &out.PoWDefensesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.KeyRotation != nil {
		in, out := &in.KeyRotation, &out.KeyRotation
		*out = new(KeyRotationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorServicePolicySpec.
func (in *TorServicePolicySpec) DeepCopy() *TorServicePolicySpec {
	if in == nil {
		return nil
	}
	out := new(TorServicePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorServicePolicyStatus) DeepCopyInto(out *TorServicePolicyStatus) {
	*out = *in
	if in.Ancestors != nil {
		in, out := &in.Ancestors, &out.Ancestors
		*out = make([]v1.PolicyAncestorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorServicePolicyStatus.
func (in *TorServicePolicyStatus) DeepCopy() *TorServicePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TorServicePolicyStatus)
	in.DeepCopyInto(out)
	return out
}
